version: '3.8'

networks:
  api:
    name: api
    driver: bridge

volumes:
  postgres:
    external: true
    name: postgres
  redis:
    external: true
    name: redis
  api:
    name: api

services:

  postgres:
    image: postgres:12.12
    hostname: postgres
    container_name: api-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '54322:5432'
    networks:
      - api
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    hostname: redis
    container_name: api-redis
    restart: always
    command: redis-server
    ports:
      - '63799:6379'
    networks:
      - api
    volumes:
      - redis:/data

  app:
    build:
      context: .
      target: development
    hostname: api
    container_name: api
    # entrypoint: ["npm", "run", "start"]
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    networks:
      - api
    volumes:
      - api:/usr/src/app
    depends_on:
      - postgres
      - redis
